# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

steps:

- script: |
    export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk-11.jdk/Contents/Home"
    mvn install
  displayName: Build App

- script: |
    cd /Users/stephen/Documents/java-goof
    snyk monitor --all-projects
  displayName: 'Snyk Open Source'

- script: |
    snyk code test | true
  displayName: 'Snyk Code'
 
- script: |
    snyk iac --report || true
  displayName: 'Snyk IaC'
