# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

steps:

- script: |
    export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk-11.jdk/Contents/Home"
    mvn install
  displayName: Build App

- script: |
    cd /Users/stephen/Documents/java-goof
    snyk monitor --all-projects
  displayName: 'Snyk Open Source'

- script: |
    cd /Users/stephen/Documents/java-goof
    snyk code test --json | snyk-to-html -o /Users/stephen/Documents/java-goof/results-code.html
  displayName: 'Snyk Code'
 
- script: |
    cd /Users/stephen/Documents/java-goof
    snyk iac test --report || true
  displayName: 'Snyk IaC'
  
- script: |
    cd /Users/stephen/Documents/java-goof
    snyk container test --file=/Users/stephen/Documents/java-goof/todolist-goof/Dockerfile || true
  displayName: 'Snyk Container'
    
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(BuildStagingDirectory)'
    Contents: 'results-code.html'
    TargetFolder: '$(BuildStagingDirectory)'


- publish: $(BuildStagingDirectory)/results-code.html
  artifact: results-code.html
