# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

pool:
  name: Default

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: default
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/todolist-goof/Dockerfile'
        tags: freshdemo/java-goof:latest
    - task: Docker@2
      displayName: Push image
      inputs:
        containerRegistry: |
          $(DockerHub)
        repository: freshdemo/java-goof
        command: push
        tags: latest
          
